### API Base URL
@baseURL = http://localhost:8080

### Create a New Note
POST {{baseURL}}/notes
Content-Type: application/json

{
  "title": "TIL: how does the internet work?",
  "content": "The internet is a pile of cables and computers that sometimes work"
}
