// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt pgtype.Timestamp
}
